// <auto-generated />
namespace Policy_Management_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class EighthMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EighthMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "202008261834205_EighthMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
